FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y && apt install -y \
    gcc \
    build-essential \
    libxerces-c-dev \
    libmysqlclient-dev \
    liblua5.4-dev \
    xutils-dev \
    libnsl-dev \
    psmisc
	
RUN mkdir /home/darkeden /home/darkeden/vs /home/darkeden/vs/src

WORKDIR /home/darkeden/vs/src
