FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y && apt install -y \
    libxerces-c3.2t64 \
    libmysqlclient21 \
    liblua5.4-0 \
    libnsl2 \
    psmisc \
    tzdata \
    && rm -rf /var/lib/apt/lists/*
#    libxerces-c-dev \
#    libmysqlclient-dev \
#    liblua5.1-dev \

#    libxerces-c3.2t64 \
#    libmysqlclient21 \
#    liblua5.1-0 \

RUN mkdir /home/darkeden /home/darkeden/vs /home/darkeden/vs/src

COPY bin /home/darkeden/vs/bin/
COPY data /home/darkeden/vs/data/
COPY docker/conf /home/darkeden/vs/conf/

WORKDIR /home/darkeden/vs/bin
